### ISSUE TITLE
UnicodeDecodeError on import

### ISSUE THREAD

**Issue by bjourne** [pymssql/pymssql#196]
Happens the first time you import pymssql 2.1.0 win32 py2.7:

```
C:\Windows\system32>python
Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymssql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_mssql.pxd", line 10, in init pymssql (pymssql.c:10798)
  File "_mssql.pyx", line 83, in init _mssql (_mssql.c:21832)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd6 in position 2: ordinal not in range(128)
```

**Comment by ympavlov** [comment]
> Can you post the output of the commands I mentioned above?

Still not fixed. Non-critical. Pymssql lastest version

```python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.gethostname()
'\xde\xf0\xe0-\xed\xee\xf3\xf2\xe1\xf3\xea'
>>> type(socket.gethostname())
<type 'str'>
>>> import pymssql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_mssql.pxd", line 10, in init pymssql (pymssql.c:12429)
  File "_mssql.pyx", line 87, in init _mssql (_mssql.c:24539)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xde in position 0: ordinal not in range(128)
>>> import sys; sys.getdefaultencoding()
'ascii'
>>> reload(sys)
<module 'sys' (built-in)>
>>> sys.setdefaultencoding('windows-1251')
>>> import pymssql
>>>
```
