### ISSUE TITLE
pymssql 2.1.0 (2.1.1) is unable to handle long username

### ISSUE THREAD

**Issue by pcdinh** [pymssql/pymssql#246]
I I think that there is a bug somewhere. Here is the proof:

```
>>> c = _mssql.connect('yxgx5mqv7u.database.windows.net:1433', 'xxxxxxxxxxxxxxxxxxx@yxgx5mqv7u', 'xxxxxxxxxxxxxxxxxxxxxx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_mssql.pyx", line 1829, in _mssql.connect (_mssql.c:19198)
  File "_mssql.pyx", line 596, in _mssql.MSSQLConnection.__init__ (_mssql.c:5855)
  File "_mssql.pyx", line 1557, in _mssql.maybe_raise_MSSQLDatabaseException (_mssql.c:15413)
_mssql.MSSQLDatabaseException: (18456, 'DB-Lib error message 18456, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed\n')
>>> c = _mssql.connect('yxgx5mqv7u.database.windows.net:1433', 'xxxxxxxxxxxxxxxxxxx1@yxgx5mqv7u', 'xxxxxxxxxxxxxxxxxxxxxx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_mssql.pyx", line 1829, in _mssql.connect (_mssql.c:19198)
  File "_mssql.pyx", line 596, in _mssql.MSSQLConnection.__init__ (_mssql.c:5855)
  File "_mssql.pyx", line 1557, in _mssql.maybe_raise_MSSQLDatabaseException (_mssql.c:15413)
_mssql.MSSQLDatabaseException: (18456, 'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed\n')

```

As you can see username "xxxxxxxxxxxxxxxxxxx1" got a different response to username 'xxxxxxxxxxxxxxxxxxx' (shorter than 1 character). Both usernames are invalid accounts.

By setting TDSDUMPCONFIG=/tmp/freetds_config.log, I found that "User name" will not be set if I use "xxxxxxxxxxxxxxxxxxx1" (the longer username: 20 chars)
- As for "xxxxxxxxxxxxxxxxxxx" (19 characters)

```
config.c:236:       client_host_name = cs1
config.c:237:         client_charset = UTF-8
config.c:238:               app_name = pymssql
config.c:239:              user_name = xxxxxxxxxxxxxxxxxxx@yxgx5mqv7u
config.c:242:                library = DB-Library
config.c:243:              bulk_copy = 0
config.c:244:      suppress_language = 0
config.c:245:          encrypt level = 0
config.c:246:          query_timeout = 5
config.c:249:               database =
config.c:250:              dump_file = /tmp/freetds.log
config.c:251:            debug_flags = 0
config.c:252:              text_size = 64512
config.c:253:           broken_dates = 0
config.c:254:     emul_little_endian = 0
config.c:255:      server_realm_name =
```
- As for "xxxxxxxxxxxxxxxxxxx1" (20 characters)

```
config.c:230:          major_version = 7
config.c:231:          minor_version = 1
config.c:232:             block_size = 0
config.c:233:               language = us_english
config.c:234:         server_charset =
config.c:235:        connect_timeout = 2
config.c:236:       client_host_name = cs1
config.c:237:         client_charset = UTF-8
config.c:238:               app_name = pymssql
config.c:239:              user_name =
config.c:242:                library = DB-Library
config.c:243:              bulk_copy = 0
config.c:244:      suppress_language = 0
config.c:245:          encrypt level = 0
config.c:246:          query_timeout = 5
config.c:249:               database =
config.c:250:              dump_file = /tmp/freetds.log
config.c:251:            debug_flags = 0
config.c:252:              text_size = 64512
config.c:253:           broken_dates = 0
config.c:254:     emul_little_endian = 0
config.c:255:      server_realm_name =
```

Long username (more than 19 characters) is accepted in tsql:

```
tsql -H yxgx5mqv7u.database.windows.net -U xxxxxxxxxxxxxxxxxxx1@yxgx5mqv7u -P xxxxxxxxxxxxxxxxxxxxxx -p 1433
```

`TDSDUMPCONFIG` log

```
config.c:229:                   port = 1433
config.c:230:          major_version = 7
config.c:231:          minor_version = 1
config.c:232:             block_size = 0
config.c:233:               language = us_english
config.c:234:         server_charset =
config.c:235:        connect_timeout = 2
config.c:236:       client_host_name = cs1
config.c:237:         client_charset = UTF-8
config.c:238:               app_name = TSQL
config.c:239:              user_name = xxxxxxxxxxxxxxxxxxx1@yxgx5mqv7u
config.c:242:                library = TDS-Library
config.c:243:              bulk_copy = 0
config.c:244:      suppress_language = 0
config.c:245:          encrypt level = 0
config.c:246:          query_timeout = 5
config.c:249:               database =
config.c:250:              dump_file = /tmp/freetds.log
config.c:251:            debug_flags = 0
config.c:252:              text_size = 64512
config.c:253:           broken_dates = 0
config.c:254:     emul_little_endian = 0
config.c:255:      server_realm_name =

```

**Comment by labynocle** [comment]
Hi there,

I created a PR to add an entry in the FAQ about this issue: (cf PR https://github.com/pymssql/pymssql/pull/470)
