### ISSUE TITLE
pymssql-2.1.1.mavericks.bottle.tar.gz causes issues with pip under old tox versions

### ISSUE THREAD

**Issue by GrahamDumpleton** [pymssql/pymssql#301]
Your decision to release:

```
pymssql-2.1.1.mavericks.bottle.tar.gz
```

with 2.2.1 is causing a situation where some pip versions under an older tox version will get confused and install the wrong package. The package then blows up on installation.

```
    Found link https://pypi.python.org/packages/source/p/pymssql/pymssql-2.1.0.zip#md5=8ffc99e86f532023fa852a880609747c (from https://pypi.python.org/simple/pymssql/), version: 2.1.0
    Found link https://pypi.python.org/packages/source/p/pymssql/pymssql-2.1.1.tar.gz#md5=98d596508cb1030eb5451c98f8e845fc (from https://pypi.python.org/simple/pymssql/), version: 2.1.1
    Skipping link http://marc-abramowitz.com/ (from https://pypi.python.org/simple/pymssql/); not a file
    Skipping link http://www.freetds.org/ (from https://pypi.python.org/simple/pymssql/); not a file
    Skipping link http://www.python.org/ (from https://pypi.python.org/simple/pymssql/); not a file
    Skipping link http://www.python.org/dev/peps/pep-0249/ (from https://pypi.python.org/simple/pymssql/); not a file
    Skipping link https://code.google.com/p/pymssql/ (from https://pypi.python.org/simple/pymssql/); not a file
    Skipping link https://github.com/pymssql/pymssql (from https://pypi.python.org/simple/pymssql/); not a file
    Skipping link https://github.com/pymssql/pymssql/blob/1.0/ChangeLog (from https://pypi.python.org/simple/pymssql/); not a file
    Skipping link https://github.com/pymssql/pymssql/commit/5033df54c1f67ad92718b4852659b07708765c9b (from https://pypi.python.org/simple/pymssql/); not a file
    Skipping link https://github.com/pymssql/pymssql/issues (from https://pypi.python.org/simple/pymssql/); not a file
    Skipping link https://github.com/pymssql/pymssql/issues/137 (from https://pypi.python.org/simple/pymssql/); not a file
    Skipping link https://groups.google.com/forum/?fromgroups#%21forum/pymssql (from https://pypi.python.org/simple/pymssql/); not a file
    Skipping link https://pypi.python.org/pypi/pymssql/1.0.2 (from https://pypi.python.org/simple/pymssql/); unknown archive format: .2
    Skipping link https://pypi.python.org/pypi/pymssql/1.0.3 (from https://pypi.python.org/simple/pymssql/); unknown archive format: .3
    Skipping link https://www.surveymonkey.com/s/KMQ8BM5 (from https://pypi.python.org/simple/pymssql/); not a file
  Using version 2.1.1.mavericks.bottle (newest of versions: 2.1.1.mavericks.bottle, 2.1.1, 2.1.0, 2.1.0, 2.1.0, 2.0.1, 2.0.1, 2.0.1, 2.0.0, 2.0.0, 2.0.0, 1.0.3, 1.0.3, 1.0.2, 1.0.2, 1.0.1, 1.0.1, 1.0.0)
  Downloading from URL https://pypi.python.org/packages/2.7/p/pymssql/pymssql-2.1.1.mavericks.bottle.tar.gz#md5=e8c7e090a1a13fefe3675d5e3feb07d9 (from https://pypi.python.org/simple/pymssql/)
  Running setup.py egg_info for package pymssql

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

    FileNotFoundError: [Errno 2] No such file or directory: '/Users/graham/Work/python_agent-database/tests/datastore_pymssql/.tox/py33-with-extensions/build/pymssql/setup.py'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

FileNotFoundError: [Errno 2] No such file or directory: '/Users/graham/Work/python_agent-database/tests/datastore_pymssql/.tox/py33-with-extensions/build/pymssql/setup.py'
```

Best I can guess is that arbitrarily chooses which of 2.2.1 and 2.2.1.mavericks.bottle to use and using mavericks one when it shouldn't as not using mavericks.

We tried a newer tox version and it worked, but it might still be luck as to which is used, not sure.

The pip version was 1.4.1 and the tox version was 1.6.1.

If created a virtualenv and use pip outside of tox was fine.

We have seen this before with one other package which was using extension to version and had to pin the version explicitly. Pinning in this case for pymssql==2.2.1 also resolves problem.

Anyway, thought you might like to know that choice of names is causing issues. I don't know what the proper solution is beyond using newer tox version.

**Comment by msabramo** [comment]
Thanks! I will remove that from PyPI.

**Comment by msabramo** [comment]
Removed. Thanks, Graham!

**Comment by GrahamDumpleton** [comment]
Hopefully that doesn't cause you an issue. Was worried the name may have been important.

Somewhere there is a document which explains rules around version string conventions to avoid issues. I can't see to find it right now. Closest I can find is:

* https://www.python.org/dev/peps/pep-0386/

The issue likely is that you use a '.' before 'mavericks' and so it sees it as a newer patch revision in older pip or something which doesn't validate is integer.

**Comment by msabramo** [comment]
Nah that was an experiment to make a Homebrew bottle. Not worth the trouble. Thanks for raising the issue!
