### ISSUE TITLE
Problems installing from pip (as of 2.1.2) (setuptools_git error)

### ISSUE THREAD

**Issue by InbarRose** [pymssql/pymssql#389]
Hi. As of the patch today (10.2.1016, version 2.12) there is a problem to install pymssql on windows with pip.

```
C:\Users\Administrator>python -m pip install --upgrade pymssql
Collecting pymssql
  Using cached pymssql-2.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools_git/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/setuptools-git/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    Couldn't find index page for 'setuptools_git' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) -- Some packages may not be found!
    No local packages or download links found for setuptools-git
    setup.py: platform.system() => 'Windows'
    setup.py: platform.architecture() => ('32bit', 'WindowsPE')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admini~1\appdata\local\temp\2\pip-build-ij6sc3\pymssql\setup.py", line 464, in <module>
        ext_modules = ext_modules(),
      File "C:\Python27\lib\distutils\core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Python27\lib\site-packages\setuptools\dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "C:\Python27\lib\site-packages\setuptools\dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 825,in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1070, in best_match
        return self.obtain(req, installer)
      File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1082, in obtain
        return installer(requirement)
      File "C:\Python27\lib\site-packages\setuptools\dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Python27\lib\site-packages\setuptools\command\easy_install.py", line 634, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools-git')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admini~1\appdata\local\temp\2\pip-build-ij6sc3\pymssql
```

I am able to install setuptools_git manually:

```
C:\Users\Administrator>pip install setuptools_git
Collecting setuptools-git
  Downloading setuptools-git-1.1.tar.gz
Installing collected packages: setuptools-git
  Running setup.py install for setuptools-git ... done
Successfully installed setuptools-git-1.1
```

But then when I try installing pymssql again....

```
C:\Users\Administrator>python -m pip install --upgrade pymssql
Collecting pymssql
  Using cached pymssql-2.1.2.tar.gz
Installing collected packages: pymssql
  Found existing installation: pymssql 2.1.1
    Uninstalling pymssql-2.1.1:
      Successfully uninstalled pymssql-2.1.1
  Running setup.py install for pymssql ... error
    Complete output from command C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\2\\pip-build-qjekzr\\pymssql\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\2\pip-sd_j6k-record\install-record.txt --single-version-externally-managed --compile:    
   setup.py: platform.system() => 'Windows'    
   setup.py: platform.architecture() => ('32bit', 'WindowsPE')
    running install
    running build
    running build_ext
    building '_mssql' extension
    error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat).Get it from http://aka.ms/vcpython27

    ----------------------------------------
  Rolling back uninstall of pymssql
Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admini~1\\appdata\\local\\temp\\2\\pip-build-qjekzr\\pymssql\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\admini~1\appdata\local\temp\2\pip-sd_j6k-record\install-record.txt --single-version-externally-managed --compile" 
failed with error code 1 in c:\users\admini~1\appdata\local\temp\2\pip-build-qjekzr\pymssql
```

**Comment by InbarRose** [comment]
The problem does not happen when i specify a version 

`python -m pip install --upgrade pymssql==2.1.1`

**Comment by ramiro** [comment]
Please wait a little so the jobs in charge of building the windows binaries
wheels can finish and upload them to pypi.

Tou can track advance by watching
https://pypi.python.org/pypi/pymssql/2.1.2#downloads and
https://ci.appveyor.com/project/pymssql/pymssql

After that, retrying installation with pip should detect these pre built
binaries  and use them instead of trying to build pymssql from source.

Regarding the setuptools_git issue there is an issue open for which we are
waiting for more information. Please add info to it if you can.

**Comment by InbarRose** [comment]
So its a temporary problem? Great. :+1:

**Comment by ramiro** [comment]
I can't reproduce this (Python 2.7.x x86 on a WIndows 7 x86_64 system):

(command line console with adminstrative rights)
```
C:\Users\Ramiro
λ pip install -U pymssql
Collecting pymssql
  Downloading pymssql-2.1.2-cp27-cp27m-win32.whl (134kB)
    100% |################################| 135kB 165kB/s
Installing collected packages: pymssql
  Found existing installation: pymssql 2.1.2.dev1
    Uninstalling pymssql-2.1.2.dev1:
      Successfully uninstalled pymssql-2.1.2.dev1
Successfully installed pymssql-2.1.2

C:\Users\Ramiro
λ pip uninstall pymssql                                                
Uninstalling pymssql-2.1.2:                                            
  c:\python27\lib\site-packages\_mssql.pyd                             
  c:\python27\lib\site-packages\pymssql-2.1.2.dist-info\description.rst
  c:\python27\lib\site-packages\pymssql-2.1.2.dist-info\installer      
  c:\python27\lib\site-packages\pymssql-2.1.2.dist-info\metadata       
  c:\python27\lib\site-packages\pymssql-2.1.2.dist-info\metadata.json  
  c:\python27\lib\site-packages\pymssql-2.1.2.dist-info\record         
  c:\python27\lib\site-packages\pymssql-2.1.2.dist-info\top_level.txt  
  c:\python27\lib\site-packages\pymssql-2.1.2.dist-info\wheel          
  c:\python27\lib\site-packages\pymssql.pyd                            
Proceed (y/n)? y                                                       
  Successfully uninstalled pymssql-2.1.2


C:\Users\Ramiro
λ pip install pymssql
Collecting pymssql
  Using cached pymssql-2.1.2-cp27-cp27m-win32.whl
Installing collected packages: pymssql
Successfully installed pymssql-2.1.2
```

**Comment by jeesyn** [comment]
Same problem happened on pymssql-2.1.3.
```bash
$ python -m pip install pymssql -U --proxy=http://liujee:Sunday_123@mwghkg.corp.knorr-bremse.com:8080
Collecting pymssql
  Using cached pymssql-2.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools_git/: timed out -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/setuptools-git/: timed out -- Some packages may not be found!
    Couldn't find index page for 'setuptools_git' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: timed out -- Some packages may not be found!
    No local packages or working download links found for setuptools_git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\liujee\AppData\Local\Temp\pip-build-9spu50r5\pymssql\setup.py", line 477, in <module>
        ext_modules = ext_modules(),
      File "c:\users\liujee\appdata\local\programs\python\python36\Lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\liujee\SVNHOM~1\BACKOF~1\venv\lib\site-packages\setuptools\dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "C:\Users\liujee\SVNHOM~1\BACKOF~1\venv\lib\site-packages\setuptools\dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "C:\Users\liujee\SVNHOM~1\BACKOF~1\venv\lib\site-packages\pkg_resources\__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "C:\Users\liujee\SVNHOM~1\BACKOF~1\venv\lib\site-packages\pkg_resources\__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "C:\Users\liujee\SVNHOM~1\BACKOF~1\venv\lib\site-packages\pkg_resources\__init__.py", line 1134, in obtain
        return installer(requirement)
      File "C:\Users\liujee\SVNHOM~1\BACKOF~1\venv\lib\site-packages\setuptools\dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Users\liujee\SVNHOM~1\BACKOF~1\venv\lib\site-packages\setuptools\command\easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_git')
    setup.py: platform.system() => 'Windows'
    setup.py: platform.architecture() => ('64bit', 'WindowsPE')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\liujee\AppData\Local\Temp\pip-build-9spu50r5\pymssql\
```

My system is Windows 7, 64bit, and the python version is `'3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]'`

**Comment by prokopst** [comment]
@shannonls I had the same issue, I managed to use a workaround - first install `setuptools-git`:
```
pip install setuptools-git
```
System is MacOS, Python 3.6.4. I use different `index-url`, which acts as a proxy to artifactory.
