### ISSUE TITLE
Parser gets confused by wildcards in quoted strings embedded in SQL queries

### ISSUE THREAD

**Issue by bkline** [pymssql/pymssql#424]
The parsing of query parameter placeholders does not properly ignore the contents of string constants in SQL queries. Here's a tiny repro:

```
>>> pymssql.__version__
u'2.1.2'
>>> pymssql.get_dbversion() # not relevant, as the execute() call never gets that far
'freetds v0.95'
>>> query = "SELECT COUNT(*) FROM document WHERE title LIKE '%summary%' AND id < %s"
>>> parms = (1500,)
>>> cursor.execute(query, parms)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymssql.pyx", line 449, in pymssql.Cursor.execute (pymssql.c:7157)
  File "_mssql.pyx", line 1009, in _mssql.MSSQLConnection.execute_query (_mssql.c:11585)
  File "_mssql.pyx", line 1040, in _mssql.MSSQLConnection.execute_query (_mssql.c:11459)
  File "_mssql.pyx", line 1157, in _mssql.MSSQLConnection.format_and_run_query (_mssql.c:12627)
  File "_mssql.pyx", line 1179, in _mssql.MSSQLConnection.format_sql_command (_mssql.c:12888)
  File "_mssql.pyx", line 1868, in _mssql._substitute_params (_mssql.c:21395)
ValueError: more placeholders in sql than params available
```

This is caused by the use of a naïve regular expression to find the positional placeholders (in _mssql.pyx):

```
_re_pos_param = re.compile(br'(%([sd]))')
...
        for count, match in enumerate(_re_pos_param.finditer(toformat)): ...
            # ....
            try:
                param_val = quoted[count]
            except IndexError:
                raise ValueError('more placeholders in sql than params available')
```

**Comment by dirkjonker** [comment]
This seems very dangerous and might make you vulnerable for SQL injection attacks when using this library.
