### ISSUE TITLE
pymssql:executemany value error - expected a simple type, a tuple or a list

### ISSUE THREAD

**Issue by milkliu66** [pymssql/pymssql#443]
`cur=conn.cursor()`
`table1='''create table grpidx(codDEL varchar(100),id int) '''`
`cur.execute(table1)`
`conn.commit()`
`data1=[]`
`for i in range(0,2):`
    `data1.append((data1.loc[i,'codDEL'],data1.loc[i,'id']))`
`data1`

> [(123,1.0),(456,2.0)]

`cur.executemany("insert into table1 values (%s,%s)",data1)`
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymssql.pyx", line 475, in pymssql.Cursor.executemany (pymssql.c:7841)
  File "pymssql.pyx", line 449, in pymssql.Cursor.execute (pymssql.c:7184)
  File "_mssql.pyx", line 1011, in _mssql.MSSQLConnection.execute_query (_mssql.c:11586)
  File "_mssql.pyx", line 1042, in _mssql.MSSQLConnection.execute_query (_mssql.c:11466)
  File "_mssql.pyx", line 1159, in _mssql.MSSQLConnection.format_and_run_query (_mssql.c:12607)
  File "_mssql.pyx", line 1181, in _mssql.MSSQLConnection.format_sql_command (_mssql.c:12868)
  File "_mssql.pyx", line 1817, in _mssql._substitute_params (_mssql.c:20647)
  File "_mssql.pyx", line 1800, in _mssql._quote_data (_mssql.c:20355)
  File "_mssql.pyx", line 1770, in _mssql._quote_or_flatten (_mssql.c:19927)
ValueError: expected a simple type, a tuple or a list

**But if I use:**
`cur.executemany("insert into table1 values (%s,%s)",[(123,1.0),(456,2.0)])`

**It's work!**
So Is it my computer's matter or pymssql package's  matter? @ramiro @damoxc 
System params: Python 3.3.5, MS SQL Server 2014, pymssql 2.1.3, Windows 10

**Comment by rsyring** [comment]
This is unlikely to be a bug in pymssql.  Please take your question to the mailing list: https://groups.google.com/forum/#!forum/pymssql

If, after getting help in the list, you believe this is a bug.  Please re-comment here with a complete test script that demonstrates the bug.  

Thanks.
