### ISSUE TITLE
Installation issues on CentOS 6.5

### ISSUE THREAD

**Issue by busfault** [pymssql/pymssql#471]
I am attempting to install pymssql on a CentOS 6.5 system.
It has a default python of 2.6x and I'm going to mess around with that.
I have python 2.7 built and installed (with ```make altinstall```) and the source is in /usr/local/src/Python-2.7.12/... 
I installed freetds:
```git clone https://github.com/FreeTDS/freetds.git```

I attempted to install pyssmql with ```python2.7 -m pip install pymssql```
Which led me down a path to here:
[https://github.com/pymssql/pymssql/issues/432](https://github.com/pymssql/pymssql/issues/432)

Now when I try to install I get the following. I have tried unsuccessfully to determine what is going wrong. 

```
python2.7 -m pip install git+https://github.com/pymssql/pymssql.git -vvv
Collecting git+https://github.com/pymssql/pymssql.git
  Cloning https://github.com/pymssql/pymssql.git to /tmp/pip-_gI8Yc-build
  Running command git clone -q https://github.com/pymssql/pymssql.git /tmp/pip-_gI8Yc-build
  Running setup.py (path:/tmp/pip-_gI8Yc-build/setup.py) egg_info for package from git+https://github.com/pymssql/pymssql.git
    Running command python setup.py egg_info
    Unable to find pgen, not compiling formal grammar.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-_gI8Yc-build/setup.py", line 86, in <module>
        Distribution(dict(setup_requires='Cython>=0.19.1'))
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 239, in __init__
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 263, in fetch_build_eggs
      File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 568, in resolve
      File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 806, in best_match
      File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 818, in obtain
      File "build/bdist.linux-x86_64/egg/setuptools/dist.py", line 313, in fetch_build_egg
      File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 609, in easy_install
      File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 639, in install_item
      File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 825, in install_eggs
      File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1031, in build_and_install
      File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 1016, in run_setup
      File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 69, in run_setup
      File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 120, in run
      File "build/bdist.linux-x86_64/egg/setuptools/sandbox.py", line 71, in <lambda>
      File "setup.py", line 248, in <module>

      File "setup.py", line 174, in compile_cython_modules
        if sys.platform == 'darwin':
      File "/tmp/easy_install-JMvWLT/Cython-0.25.1/Cython/Distutils/__init__.py", line 1, in <module>
      File "/tmp/easy_install-JMvWLT/Cython-0.25.1/Cython/Distutils/build_ext.py", line 5, in <module>
      File "build/bdist.linux-x86_64/egg/setuptools/command/build_ext.py", line 48, in <module>
    TypeError: Error when calling the metaclass bases
        str() takes at most 1 argument (3 given)
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-_gI8Yc-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-_gI8Yc-build/

```

**Comment by busfault** [comment]
I have solved some of the issue, cython was not installed, for some reason it seemed to be when I looked at pip but then I installed cython again and I got a little further. However I am still running into an issue:

```
Collecting git+https://github.com/pymssql/pymssql.git
  Cloning https://github.com/pymssql/pymssql.git to /tmp/pip-qe0qnT-build
  Running command git clone -q https://github.com/pymssql/pymssql.git /tmp/pip-qe0qnT-build
  Running setup.py (path:/tmp/pip-qe0qnT-build/setup.py) egg_info for package from git+https://github.com/pymssql/pymssql.git
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-qe0qnT-build/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
      File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/__init__.py", line 1, in <module>
        from Cython.Distutils.build_ext import build_ext
      File "/usr/local/lib/python2.7/site-packages/Cython/Distutils/build_ext.py", line 5, in <module>
        from setuptools.command.build_ext import build_ext as _build_ext
      File "build/bdist.linux-x86_64/egg/setuptools/command/build_ext.py", line 48, in <module>
    TypeError: Error when calling the metaclass bases
        str() takes at most 1 argument (3 given)
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-qe0qnT-build/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-qe0qnT-build/
```

**Comment by busfault** [comment]
So,
I eventually got it worked out.
What happened was I was attempting to run pip via sudo. When I logged in as root the install went smoothly.
Secondly i ended up finding this issue:
[](https://github.com/pymssql/pymssql/issues/8)

After that, seems to be working OKAY.
