### ISSUE TITLE
Older Python (3.4): "bytes object has no attribute 'encode'" when working with connect statements.

### ISSUE THREAD

**Issue by teward** [pymssql/pymssql#521]
Yes, I know, Python 3.4 is *old* and *decrepit* but there's an older system here that we are stuck with that uses Python 3.4.

When attempting to use `pymssql`, we get traceback indicating that there is an attribute error somewhere, such that we get this error traceback:

```
Traceback (most recent call last):
  File "./threader.py", line 642, in <module>
    main()
  File "./threader.py", line 240, in main
    if not Database.server_available():
  File "/home/threader/Threader3/bin/ThreaderLib/remote/_Database.py", line 38, in server_available
    db_password=db_password)
  File "/home/threader/Threader3/bin/ThreaderLib/remote/_Database.py", line 63, in open_connection
    return pymssql.connect(host=db_host, user=db_user, password=db_password)
  File "pymssql.pyx", line 635, in pymssql.connect (pymssql.c:10734)
  File "_mssql.pyx", line 1902, in _mssql.connect (_mssql.c:21821)
  File "_mssql.pyx", line 569, in _mssql.MSSQLConnection.__init__ (_mssql.c:6135)
AttributeError: 'bytes' object has no attribute 'encode'
```

Somewhere along the line, you're attempting to convert a string to bytes, is my guess, but that's not going to work for a `bytes` object.  Any chance this is an issue in `pymssql` that's fixable for older-software compatibility purposes?  Or should I be hunting some other MSSQL interface library?

**Comment by teward** [comment]
DISREGARD.  The issue is that the password argument is being passed in as bytes.  Looks to be a Python3 oddity when working with encoded strings.
