### ISSUE TITLE
"ImportError: libsybdb.so.5: cannot open shared object file" on Lambda (AWS Linux AMI)

### ISSUE THREAD

**Issue by complangorous** [pymssql/pymssql#533]
After using Zappa to push an app to a Lambda from an Linux AMI EC2 instance, I encountered the following error,

`libsybdb.so.5: cannot open shared object file: No such file or directory: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 510, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 238, in lambda_handler
    handler = cls()
  File "/var/task/handler.py", line 129, in __init__
    self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/tmp/sql-test/sql_test.py", line 4, in <module>
    import pymssql
ImportError: libsybdb.so.5: cannot open shared object file: No such file or directory
`

 Any attempt to invoke it will fail on reference to pymssql (this is also the case for pyodbc). The above stack trace failed at the import statement of this script,

`#!/usr/bin/env python

import pymssql
import pyodbc

def main():
    print('test')

if __name__ == "__main__":
    main()
`

Like I stated before, my environment is Linux AMI, and my virtualenv has the following packages. 
`argcomplete==1.9.2
awscli==1.14.53
base58==0.2.4
boto3==1.6.6
botocore==1.9.6
certifi==2018.1.18
cfn-flip==1.0.1
chardet==3.0.4
click==6.7
colorama==0.3.7
Cython==0.27.3
docutils==0.14
durationpy==0.5
future==0.16.0
hjson==3.0.1
idna==2.6
jmespath==0.9.3
kappa==0.6.0
lambda-packages==0.19.0
placebo==0.8.1
pyasn1==0.4.2
pymssql==2.2.0.dev0
PyMySQL==0.8.0
pyodbc==4.0.22
python-dateutil==2.6.1
python-slugify==1.2.4
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.13
six==1.11.0
toml==0.9.4
tqdm==4.19.1
troposphere==2.2.0
Unidecode==1.0.22
urllib3==1.22
Werkzeug==0.12
wsgi-request-logger==0.4.6
zappa==0.45.1
`

 I've been trying to hack this for a few days and tried (this)[https://stackoverflow.com/questions/39395548/how-to-configure-pymssql-with-ssl-support-on-ubuntu-16-04-lts] , but to no avail. Most other documentations of pymssql issues like this seem to have issues importing pymssql in the interpretor, so it seems worth mentioning that this is _not_ the case: importing pymssql with my virtual environment's interpretor does not yield an error. 

 Thanks, and please let me know if there's any additional information I can provide.

**Comment by itcakm** [comment]
I am facing the same problem.

`[1527471091670] Instancing..
[1527471093013] libsybdb.so.5: cannot open shared object file: No such file or directory: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 509, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 237, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 129, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/var/task/app.py", line 10, in <module>
  import pymssql
ImportError: libsybdb.so.5: cannot open shared object file: No such file or directory

`

python 3.6
AWS Lambda

**Comment by weiliangz** [comment]
I'm facing the same issue here.
`libsybdb.so.5: cannot open shared object file: No such file or directory`

Did you guys solve this issue? 

Thanks!

**Comment by complangorous** [comment]
@weiliangz No dice :/ 

I should also mention that since posting this I tried building pymssql in a Redhat ec2 instance (because it's supposed to be the same environment as a Lambda) to see if it'd create Lambda-compatible precompiled code, but that didn't work either.

**Comment by weiliangz** [comment]
@complangorous Thanks for your reply. 
Ah yeah, I also did the exactly same try as what you did. I built the pymssql in an Amazon Linux instance and tried to use that, but didn't work.

**Comment by itcakm** [comment]
I managed to build it and uploaded it here:

https://s3-ap-southeast-1.amazonaws.com/cti-static-files/lib/pymssql.zip

**Comment by weiliangz** [comment]
`libsybdb.so.5: cannot open shared object file` error was resolved by including the "libsybdb.so.5" shared object in the deployment package

**Comment by complangorous** [comment]
@itcakm Could you share the steps to your build?

**Comment by weiliangz** [comment]
@complangorous Here's my steps to build, and I was using Python 3.6

```
sudo yum install python36-devel
sudo yum install libffi-devel
sudo yum install openssl-devel
sudo yum install libxslt-devel
sudo yum install freetds-devel
sudo yum install gcc
pip3 install pymssql
```
Some of the them might not be needed but I'm not sure, so I just installed them according to the error messages. However, perhaps the `libsybdb.so.5` is still not there after installing all these. 

What I did is to locate the `libsybdb.so.5` in my instance and include that into the deployment package with Lambda.

Hope that helps.

**Comment by raul-barreto** [comment]
Hi,

I got the same issue but I solve doing the following steps:

Install the pymssql using pip: **pip install mpymssql**

And after installed, I tried to uninstall and got from pip the folders used by pymssql (including libsybdb file). I copied the content of the folders, zipped to lambda and now it works with Lambda.

If you want to simply download the latest pymssql, I uploaded here the pymssql 2.1.4

[pymssql.zip](https://github.com/pymssql/pymssql/files/2710402/pymssql.zip)
