### ISSUE TITLE
Build fails on Mac OSX

### ISSUE THREAD

**Issue by adriannye** [pymssql/pymssql#578]
I have Mac OSX 10.12.6 (Sierra).

Using python 3.6, and the latest pip (18.0), and tox (3.2.1).

I'm building from the master branch instead of the latest release to avoid issue #520.

The pip install command that tox issues and results is as follows: 

```
 cmdargs: ['/Users/anye/src/core/unver/webapi/.tox/py36-local-server/bin/pip', 'install', '--no-index', '--no-build-isolation', 'git+ssh://git@stash.dimensional.com/itsme/dfa.git', '-rrequirements.txt', 'Cython', 'ddt==1.0.1', 'model_mommy==1.2.6', 'coverage', 'cov-core', 'py', 'pytest', 'pytest-cov']

Collecting Cython
Collecting ddt==1.0.1
Collecting model_mommy==1.2.6
Collecting coverage
Collecting cov-core
Collecting py
Collecting pytest
Collecting pytest-cov
...Collects more packages here, omitted...
Collecting pymongo==3.6.1 (from -r requirements.txt (line 27))
Obtaining pymssql from git+https://github.com/pymssql/pymssql.git#egg=pymssql (from -r requirements.txt (line 30))
  Cloning https://github.com/pymssql/pymssql.git to ./.tox/py36-local-server/src/pymssql
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/anye/src/core/unver/webapi/.tox/py36-local-server/src/pymssql/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
```

Note that Cython is collected before attempting to collect pymssql yet it can't find Cython.  Also, if I manually pip install Cython in the tox virtualenv before running tox, it makes no difference, it still doesn't find Cython.

I have found no workaround.

**Comment by AlexHagerman** [comment]
Are you able to reproduce this in a stand alone virtual environment with the requirements (Cython, pytest, etc) on your machine running setup.py outside of tox?

**Comment by adriannye** [comment]
Yes, the same thing happens with a fresh virtualenv not using tox.   However if I run "pip install Cython" first before a separate pip install of the rest of the packages, the build succeeds.   

If I could figure out how to make tox do the Cython install first, that would be a usable workaround.

**Comment by AlexHagerman** [comment]
Are you using this tox file? https://github.com/pymssql/pymssql/blob/master/tox.ini

**Comment by adriannye** [comment]
No, I am using the tox.ini for my own project:  https://pastebin.com/BfmruCwv

I also have Cython listed as a dependency but it does not get fully installed before pymssql is collected, so the import does not succeed.

**Comment by AlexHagerman** [comment]
I'll look into how we can address this in `setup.py` a quick google search makes it appear to be a some what common issue with `setup.py` and Cython as a dependency. This will probably be addressed after I finish the 2.1.4 RC review and CI/CD updates I'm working on if you want me to look into it. If you want to dig in this is probably a good first time issue to work on and the links I've provided give some details.

**Comment by adriannye** [comment]
I'll open a pull request for a setup.py change that fixes it.

**Comment by adriannye** [comment]
Pull request #585, which solves the problem on OSX, but it doesn't pass the CI tests because when it uses the installed Cython it can't find sqlfront.h.  It seems the CI environment needs to have freetds-devel package installed.

**Comment by ju5t** [comment]
Our workaround installs freetds-dev in our CI-container and uses a trick in tox to install Cython before it installs requirements.txt. Not the prettiest perhaps, but it works.

```
[tox]
indexserver =
    preinstall = https://pypi.python.org/simple

[base]
deps = 
    :preinstall: Cython
...
```

This is on Debian 9.

**Comment by adriannye** [comment]
@ju5t  your tox hack also worked for me, but indexserver is deprecated and setuptools doc says it will be removed.

**Comment by cscetbon** [comment]
@n0mn0m still got the issue on pip 20.1. Why `pymssql` does not simply install `cython` as a requirement ? It's really annoying to have to install Cython separately. Why can 't you go back to https://github.com/pymssql/pymssql/blob/master/setup.py#L84-L87 ?

**Comment by n0mn0m** [comment]
@cscetbon https://github.com/pymssql/pymssql/issues/668
