### ISSUE TITLE
platform.linux_distribution is removed in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [pymssql/pymssql#586]
`setup.py` uses `platform.linux_distribution` which was deprecated in Python 3.7 and removed in Python master branch that will be released as Python 3.8 which makes pymssql not compatible with upstream.

Upstream python issue : https://bugs.python.org/issue28167

Traceback on doing `pip install pymssql` with CPython master

```   
 /home/karthi/cpython/foo_env/lib/python3.8/site-packages/setuptools/dist.py:36: DeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DeprecationWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-crzkv91l/pymssql/setup.py", line 160, in <module>
        print("setup.py: platform.linux_distribution() => %r" % (platform.linux_distribution(),))
    AttributeError: module 'platform' has no attribute 'linux_distribution'
    setup.py: platform.system() => 'Linux'
    setup.py: platform.architecture() => ('64bit', 'ELF')
```

Thanks

**Comment by AlexHagerman** [comment]
Thanks for the heads up. We will look into it once other issues have been resolved. For anybody interested the 3.8 release schedule is here:

https://www.python.org/dev/peps/pep-0569/

**Comment by PH89** [comment]
Fixed with PR #659

**Comment by diegobmd** [comment]
Any expectation when will be released? 

I had the same problem

	python3.8 -m pip install pymssql==2.1.4
	Collecting pymssql==2.1.4
	  Using cached https://files.pythonhosted.org/packages/2e/81/99562b93d75f3fc5956fa65decfb35b38a4ee97cf93c1d0d3cb799fffb99/pymssql-2.1.4.tar.gz
	    ERROR: Command errored out with exit status 1:
	     command: /usr/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u6ttcw8c/pymssql/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u6ttcw8c/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-u6ttcw8c/pymssql/pip-egg-info
	         cwd: /tmp/pip-install-u6ttcw8c/pymssql/
	    Complete output (9 lines):
	    /home/dmbaldani/.local/lib/python3.8/site-packages/setuptools/dist.py:46: DistDeprecationWarning: Do not call this function
	      warnings.warn("Do not call this function", DistDeprecationWarning)
	    Traceback (most recent call last):
	      File "<string>", line 1, in <module>
	      File "/tmp/pip-install-u6ttcw8c/pymssql/setup.py", line 160, in <module>
	        print("setup.py: platform.linux_distribution() => %r" % (platform.linux_distribution(),))
	    AttributeError: module 'platform' has no attribute 'linux_distribution'
	    setup.py: platform.system() => 'Linux'
	    setup.py: platform.architecture() => ('64bit', 'ELF')
	    ----------------------------------------
	ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by wesm** [comment]
A 2.1.5 release with Python 3.8 can be made but will require some alterations to the CI scripts to produce packages for 3.8. PRs would be welcome. I haven't had time to investigate thoroughly how to produce the wheels

**Comment by kraptor** [comment]
Is there any update on this one?

**Comment by flotho** [comment]
Some say that it could come from pip itself. Any workaround ?

**Comment by Djones4822** [comment]
Installed Ubuntu Server 20.04 and python3.8 was default installed, running into the same issue now. Will begin looking into compiling a 3.8 wheel

**Comment by Jordan-Gillard** [comment]
I'm having the same issue here. For the time being I'll remove the one walrus operator and downgrade the project to python3.7,  but I'd definitely like to be informed when the 3.8 wheel is compiled.

**Comment by wesm** [comment]
This project does not currently have package maintainers. There won't be a 3.8 wheel until that changes

**Comment by nicocan** [comment]
I had the same problem. But I downloaded the source code and install from it, with pip install /<dir with source>
Remenber install befire the the python developer packge.

**Comment by rufaidahsalim** [comment]
> Installed Ubuntu Server 20.04 and python3.8 was default installed, running into the same issue now. Will begin looking into compiling a 3.8 wheel

Were you able to resolve this?

**Comment by termim** [comment]
Yes, Python 3.8 wheels are available on pypi.
