### ISSUE TITLE
apple silcon Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib

### ISSUE THREAD

**Issue by lulululuej** [pymssql/pymssql#712]
Hi,
i got an issue about my mac M1 silcon, because of M1 homebrew is under /opt/homebrew, when i install pymssql via 'pip install pymssql' and import to VScode, it return the error below.
--------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karenchow/ConnectMssql.py", line 1, in <module>
    import pymssql
  File "/Users/karenchow/opt/anaconda3/envs/Project1/lib/python3.9/site-packages/pymssql/__init__.py", line 3, in <module>
    from ._pymssql import *
ImportError: dlopen(/Users/karenchow/opt/anaconda3/envs/Project1/lib/python3.9/site-packages/pymssql/_pymssql.cpython-39-darwin.so, 2): **Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib**
  Referenced from: /Users/karenchow/opt/anaconda3/envs/Project1/lib/python3.9/site-packages/pymssql/_pymssql.cpython-39-darwin.so
  Reason: image not found
--------------------------------------------------------------------------------------------------------------
And i check the file **libssl.1.1.dylib** is under /opt/homebrew/opt/openssl@1.1/lib but not in the /usr/local, so how can i do to loaded the lib?

Thanks.

**Comment by termim** [comment]
Do you have OpenSSL installed in homebrew?

**Comment by lulululuej** [comment]
> Do you have OpenSSL installed in homebrew?

Yes, OpenSSL is in my /opt/homebrew/opt/openssl@1.1

**Comment by termim** [comment]
If you have python installed in homebrew, could you try to use it instead of anaconda's  to load pymssql?

**Comment by termim** [comment]
Also could you run 
```python -c "import ssl; print(ssl.OPENSSL_VERSION)"```
and show here the result?

**Comment by lulululuej** [comment]
> If you have python installed in homebrew, could you try to use it instead of anaconda's to load pymssql?

(base) karenchow@Karens-Air ~ % /opt/homebrew/bin/python3 /Users/karenchow/ConnectMssql.py
Traceback (most recent call last):
  File "/Users/karenchow/ConnectMssql.py", line 1, in <module>
    import pymssql
  File "/opt/homebrew/lib/python3.9/site-packages/pymssql/__init__.py", line 3, in <module>
    from ._pymssql import *
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/pymssql/_pymssql.cpython-39-darwin.so, 2): no suitable image found.  Did find:
        /opt/homebrew/lib/python3.9/site-packages/pymssql/_pymssql.cpython-39-darwin.so: mach-o, but wrong architecture
        /opt/homebrew/lib/python3.9/site-packages/pymssql/_pymssql.cpython-39-darwin.so: mach-o, but wrong architecture

when i use python3.9 install in homebrew, it result

**Comment by lulululuej** [comment]
> python -c "import ssl; print(ssl.OPENSSL_VERSION)"

(base) karenchow@Karens-Air ~ % python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1k  25 Mar 2021

**Comment by paulosouzainfo** [comment]
Above, i have the same response and do not understand this same error in equal conditions

> > python -c "import ssl; print(ssl.OPENSSL_VERSION)"
> 
> (base) karenchow@Karens-Air ~ % python -c "import ssl; print(ssl.OPENSSL_VERSION)"
> OpenSSL 1.1.1k 25 Mar 2021

**Comment by LeonardoGentile** [comment]
I'm experiencing something similar, I'm on an old macbook pro (2015), python 3.5.2, and never had a problem before

I've recently upgrade openssl (1.1) installed via brew. 
Since this happened pymssql stopped working.
I've re-installed `pymssql` but I get the same error:

```
Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/opt/freetds@0.91/lib/libsybdb.5.dylib
  Reason: image not found
`
``
In fact inside `/usr/local/opt/openssl/lib/` the version found is `libssl.1.1.dylib` not version `1.00` as requested by mssql 

Anything I can do to fix this?

**Comment by buckstephenh** [comment]
python3.9 -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 1.1.1q  5 Jul 2022

but I get

 ld: library not found for -lssl 

when I run pip install pymssql
