### ISSUE TITLE
Latest (2.2.1) will not import into my project. Was previously working on older version 2.1.5

### ISSUE THREAD

**Issue by apocalypse2012** [pymssql/pymssql#718]
Mac OS 10.15.7 

from pymssql import _mssql
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/Development/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/rstewart/Depot/acc_elt_pipeline/venv/lib/python3.9/site-packages/pymssql/__init__.py", line 3, in <module>
    from ._pymssql import *
  File "/Applications/Development/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "src/pymssql/_pymssql.pyx", line 1, in init pymssql._pymssql
  File "/Applications/Development/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Users/rstewart/Depot/acc_elt_pipeline/venv/lib/python3.9/site-packages/pymssql/_mssql.cpython-39-darwin.so, 2): Symbol not found: _iconv
  Referenced from: /Users/rstewart/Depot/acc_elt_pipeline/venv/lib/python3.9/site-packages/pymssql/_mssql.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/rstewart/Depot/acc_elt_pipeline/venv/lib/python3.9/site-packages/pymssql/_mssql.cpython-39-darwin.so
import pymssql
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/Development/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/rstewart/Depot/acc_elt_pipeline/venv/lib/python3.9/site-packages/pymssql/__init__.py", line 3, in <module>
    from ._pymssql import *
  File "/Applications/Development/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "src/pymssql/_pymssql.pyx", line 1, in init pymssql._pymssql
  File "/Applications/Development/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: dlopen(/Users/rstewart/Depot/acc_elt_pipeline/venv/lib/python3.9/site-packages/pymssql/_mssql.cpython-39-darwin.so, 2): Symbol not found: _iconv
  Referenced from: /Users/rstewart/Depot/acc_elt_pipeline/venv/lib/python3.9/site-packages/pymssql/_mssql.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/rstewart/Depot/acc_elt_pipeline/venv/lib/python3.9/site-packages/pymssql/_mssql.cpython-39-darwin.so

**Comment by termim** [comment]
Could you try the wheel from [test.pypi](https://test.pypi.org/project/pymssql/2.2.2.dev7/#files)?

**Comment by termim** [comment]
Should be fixed in edc76e6b
