### ISSUE TITLE
Cannot connect to named instance of SQL Server

### ISSUE THREAD

**Issue by captain-woof** [pymssql/pymssql#719]
**Describe the bug**
Trying to connect to a named instance of SQL server always fails, throwing a **`Adaptive Server is unavailable or does not exist` error.**

**To Reproduce**
```
import pymssql
conn = pymssql.connect(server=r'HOSTNAME\INSTANCE',password=password,user=username,port=port)
```

**Expected behavior**
A successful connection.

**Current Behavior**
These exceptions are thrown:
```
Traceback (most recent call last):
  File "src/pymssql.pyx", line 636, in pymssql.connect
  File "src/_mssql.pyx", line 1964, in _mssql.connect
  File "src/_mssql.pyx", line 682, in _mssql.MSSQLConnection.__init__
  File "src/_mssql.pyx", line 1690, in _mssql.maybe_raise_MSSQLDatabaseException
_mssql.MSSQLDatabaseException: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (HOSTNAME)\nDB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (HOSTNAME)\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pymssql.pyx", line 642, in pymssql.connect
pymssql.OperationalError: (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (HOSTNAME)\nDB-Lib error message 20009, severity 9:\nUnable to connect: Adaptive Server is unavailable or does not exist (HOSTNAME)\n')
```

**Context (Environment)**
 - What are the OS, Python and FreeTDS versions?
 Kali 2021.2, Python 3.9.2

 - please include the output of the following command:
    `/<path to your python>/python -c "import pymssql; print(pymssql.version_info())"`
```
AttributeError: module 'pymssql' has no attribute 'version_info'
```

**Comment by termim** [comment]
What is the pymssql version?

**Comment by captain-woof** [comment]
Latest as of now.

**Comment by termim** [comment]
In latest `pymssql` has `version_info`.

**Comment by captain-woof** [comment]
Apologies, that was an older output I posted.
Here's the `version_info`:
```
System:
platform.system()       : Linux
platform.architecture() : ('64bit', 'ELF')
platform.libc_ver()     : ('glibc', '2.31')
Python:
sys.version             : 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
pymssql:
VERSION            : (2, 2, 1)
version            : 2.2.1
full_version       : 2.2.1
dbversion          : freetds v1.2.18
_mssql:
VERSION            : (2, 2, 1)
version            : 2.2.1
full_version       : 2.2.1
dbversion          : freetds v1.2.18
login_timeout      : 60
min_error_severity : 6
```

**Comment by termim** [comment]
The traceback also from the "old" output?
Can you connect using tsql?
What is the SQL server version?
Was pymssql installed from PyPI?

**Comment by jealcuna** [comment]
I could solve updating to 2.2.2 version
