### ISSUE TITLE
Can not install on M1 Device

### ISSUE THREAD

**Issue by veroyatnost** [pymssql/pymssql#727]
**Describe the bug**
Can not install on M1 Device

**To Reproduce**
pip install pymssql 

**Current Behavior**
  Building wheel for pymssql (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/4g/00dh4bh571z5h5sfmsjlkz580000gn/T/tmpjdbqplkm
       cwd: /private/var/folders/4g/00dh4bh571z5h5sfmsjlkz580000gn/T/pip-install-4lhf0hp3/pymssql_f905ade125c04a30a66cad735318b169
  Complete output (24 lines):
  setup.py: platform.system() => Darwin
  setup.py: platform.architecture() => ('64bit', '')
  setup.py: platform.libc_ver() => ('', '')
  setup.py: include_dirs => []
  setup.py: library_dirs => []
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-universal2-3.9
  creating build/lib.macosx-10.9-universal2-3.9/pymssql
  copying src/pymssql/__init__.py -> build/lib.macosx-10.9-universal2-3.9/pymssql
  running build_ext
  cythoning src/pymssql/_mssql.pyx to src/pymssql/_mssql.c
  cythoning src/pymssql/_pymssql.pyx to src/pymssql/_pymssql.c
  building 'pymssql._mssql' extension
  creating build/temp.macosx-10.9-universal2-3.9
  creating build/temp.macosx-10.9-universal2-3.9/src
  creating build/temp.macosx-10.9-universal2-3.9/src/pymssql
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/opt/homebrew/opt/freetds/include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/pymssql/_mssql.c -o build/temp.macosx-10.9-universal2-3.9/src/pymssql/_mssql.o -DMSDBLIB
  gcc -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g -L/opt/homebrew/opt/freetds/lib -I/opt/homebrew/opt/freetds/include build/temp.macosx-10.9-universal2-3.9/src/pymssql/_mssql.o -lsybdb -lssl -lcrypto -o build/lib.macosx-10.9-universal2-3.9/pymssql/_mssql.cpython-39-darwin.so
  ld: library not found for -lssl
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pymssql

**Context (Environment)**
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by termim** [comment]
You do not have OpenSSL installed: **ld: library not found for -lssl**
Try to install it and iconv:
```
brew install openssl@1.1
brew install libiconv
```

**Comment by veroyatnost** [comment]
> You do not have OpenSSL installed: **ld: library not found for -lssl** Try to install it and iconv:
> 
> ```
> brew install openssl@1.1
> brew install libiconv
> ```

Thanks, but that is wried. I have used brew to install openssl, libiconv, and freetds, I still got this message even I have export the PATH

The error message has two versions:

1. like above 
2. lack of sql.h

**Comment by BigCheeze45** [comment]
Jotting this here incase it's helpful to anyone. I got the 2nd version (lack of sql.h) of this error. However, I'm using a docker container - specifically the [python:3.6.8 image](https://hub.docker.com/_/python?tab=description&page=1&ordering=last_updated)

To get it working, I:
1. [install rosetta, per Docker doc](https://docs.docker.com/desktop/mac/apple-silicon/#system-requirements)
2. again, per the docs, use `--platform linux/amd64` to run the Intel image using emulation

So, if trying to run natively: make sure rosetta is installed and if possible specify the platform/architecture as amd64.

**Comment by ChenTsungYu** [comment]
I've fixed the problem after executing `python3 -m pip install pymssql  --no-use-pep517`

**Comment by anishpavaskar** [comment]
@ChenTsungYu  thanks your method worked

**Comment by albdv** [comment]
```
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
```
adding this to env helps to solve an issue

**Comment by aaisino** [comment]
@albdv  Still facing same issue..

**Comment by termim** [comment]
> @albdv Still facing same issue..

Please provide the whole output.

**Comment by awaisdar001** [comment]
```
python3 -m pip install pymssql --no-use-pep517
Defaulting to user installation because normal site-packages is not writeable
Collecting pymssql
  Using cached pymssql-2.2.5.tar.gz (170 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tgsm77r9/pymssql_2489552aca9f4bd198b8a7023b4d8de4/setup.py", line 45, in <module>
          from Cython.Distutils import build_ext as _build_ext
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details
```

**Comment by ckalas** [comment]
similar to @albdv but the path had to be different for homebrew running on M1
export LDFLAGS="-L/opt/homebrew/opt/openssl/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl/include"

**Comment by anyidea** [comment]
this solve my issue
```
brew install freetds openssl
export LDFLAGS="-L/opt/homebrew/opt/freetds/lib -L/opt/homebrew/opt/openssl@3/lib"
export CFLAGS="-I/opt/homebrew/opt/freetds/include"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
python -m pip install pymssql
```

**Comment by adjaythakoerdien** [comment]
> this solve my issue
> 
> ```
> brew install freetds openssl
> export LDFLAGS="-L/opt/homebrew/opt/freetds/lib -L/opt/homebrew/opt/openssl@3/lib"
> export CFLAGS="-I/opt/homebrew/opt/freetds/include"
> export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
> python -m pip install pymssql
> ```

This worked for me, thanks! :-D

**Comment by myndsol-naveen** [comment]
> this solve my issue
> 
> ```
> brew install freetds openssl
> export LDFLAGS="-L/opt/homebrew/opt/freetds/lib -L/opt/homebrew/opt/openssl@3/lib"
> export CFLAGS="-I/opt/homebrew/opt/freetds/include"
> export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
> python -m pip install pymssql
> ```

Tum to Ram nikle dost🫡

**Comment by rroline-koresights** [comment]
> this solve my issue
> 
> ```
> brew install freetds openssl
> export LDFLAGS="-L/opt/homebrew/opt/freetds/lib -L/opt/homebrew/opt/openssl@3/lib"
> export CFLAGS="-I/opt/homebrew/opt/freetds/include"
> export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
> python -m pip install pymssql
> ```

This worked for me as well :) Thanks!

**Comment by alison985** [comment]
> this solve my issue
> 
> ```
> brew install freetds openssl
> export LDFLAGS="-L/opt/homebrew/opt/freetds/lib -L/opt/homebrew/opt/openssl@3/lib"
> export CFLAGS="-I/opt/homebrew/opt/freetds/include"
> export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
> python -m pip install pymssql
> ```

This doesn't work in Docker on M1 because, at the least, you can't install Homebrew. See: https://docs.brew.sh/Homebrew-on-Linux#arm-unsupported

I've been through this thread multiple times and tried all the various suggestions. I'm using the Docker image `python:3.11.2-slim-bullseye`. **While none of the following works**, it is a translation of getting the above into Docker on M1.

```bash
# in docker container
pip install pymssql
# receive error message (see it pasted below)

# on mac, not in docker
softwareupdate --install-rosetta
# approve Apple agreement

# re-enter Docker container 

# libc6-dev substitutes for libiconv https://askubuntu.com/questions/898826/why-is-there-no-libiconv-package-in-ubuntu
apt-get update && apt-get install wget libc6-dev openssl 
# how to install freetds without homebrew from https://stackoverflow.com/a/51340351 
# find latest version of FreeTDS ftp://ftp.freetds.org/pub/freetds/stable/
wget ftp://ftp.freetds.org/pub/freetds/stable/freetds-1.3.18.tar.gz
tar -xzf freetds-1.3.18.tar.gz
cd freetds-1.3.18
./configure --prefix=/usr/local
sudo make
sudo make install

#may or may not duplicate freetds install above
apt install -y freetds-bin

# these pip variations also don't work
# pip install --platform linux/amd64 --no-deps pymssql
# pip install pymssql --no-use-pep517

# pymssql depends on Cython, but I'm not convinced it requires the requirement correctly because the error is in Cython compiling
# referenced https://cython.readthedocs.io/en/latest/src/quickstart/install.html
# apt list --installed showed Cython but pip list didn't
pip install Cython
```

The environment variable paths above assume Homebrew, so what about the ones from @albdv? 
> export LDFLAGS="-L/usr/local/opt/openssl/lib"
> export CPPFLAGS="-I/usr/local/opt/openssl/include"

Unfortunately /usr/local/opt directory doesn't exist. Any other thoughts on setting LDFLAG,  CFLAGS, and CPPFLAGS?

Here's the current response to `pip install pymssql`.
```bash
Collecting pymssql
  Using cached pymssql-2.2.7.tar.gz (170 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pymssql
  Building wheel for pymssql (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pymssql (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [127 lines of output]
      prefix='/usr/local'
      setup.py: platform.system() => Linux
      setup.py: platform.architecture() => ('64bit', '')
      setup.py: platform.libc_ver() => ('glibc', '2.31')
      setup.py: include_dirs => ['/usr/local/include']
      setup.py: library_dirs => ['/usr/local/lib']
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/pymssql
      copying src/pymssql/__init__.py -> build/lib.linux-aarch64-cpython-311/pymssql
      running build_ext
      warning: src/pymssql/_mssql.pyx:27:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:28:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:29:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:30:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:31:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:32:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:35:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:36:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:38:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:82:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:230:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:264:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:333:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:831:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:919:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:1005:12: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:1379:16: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src/pymssql/_mssql.pyx:1713:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      cdef void init_mssql():
          if dbinit() == FAIL:
              raise MSSQLDriverException("dbinit() failed")
      
          dberrhandle(err_handler)
                      ^
      ------------------------------------------------------------
      
      src/pymssql/_mssql.pyx:2173:16: Cannot assign type 'int (DBPROCESS *, int, int, int, char *, char *) except? -1 nogil' to 'EHANDLEFUNC'
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef void init_mssql():
          if dbinit() == FAIL:
              raise MSSQLDriverException("dbinit() failed")
      
          dberrhandle(err_handler)
          dbmsghandle(msg_handler)
                      ^
      ------------------------------------------------------------
      
      src/pymssql/_mssql.pyx:2174:16: Cannot assign type 'int (DBPROCESS *, DBINT, int, int, char *, char *, char *, LINE_T) except? -1 nogil' to 'MHANDLEFUNC'
      Compiling src/pymssql/_mssql.pyx because it changed.
      [1/1] Cythonizing src/pymssql/_mssql.pyx
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 289, in <module>
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 181, in build_extensions
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
                    ^^^^^^^^^^
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-svew26c5/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: src/pymssql/_mssql.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymssql
Failed to build pymssql
ERROR: Could not build wheels for pymssql, which is required to install pyproject.toml-based projects
```

**Comment by albdv** [comment]
@alison985 on m1 mac run docker container with `--platform linux/amd64` command line options to solve an issue:
```
❯ docker run --platform linux/amd64 -ti python:3.11.2-slim-bullseye bash                                                                     
Unable to find image 'python:3.11.2-slim-bullseye' locally
3.11.2-slim-bullseye: Pulling from library/python
f1f26f570256: Pull complete
2d2b01660885: Pull complete
e4e8e4c0b0e1: Pull complete
1ba60f086308: Pull complete
3c2fccf90be1: Pull complete
Digest: sha256:2f749ef90f54fd4b3c77cde78eec23ab5b8199d9ac84e4ced6ae523ef223ef7b
Status: Downloaded newer image for python:3.11.2-slim-bullseye
root@581bdd7fb945:/# pip install pymssql
Collecting pymssql
  Downloading pymssql-2.2.7-cp311-cp311-manylinux_2_24_x86_64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 8.3 MB/s eta 0:00:00
Installing collected packages: pymssql
Successfully installed pymssql-2.2.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.2
[notice] To update, run: pip install --upgrade pip
root@581bdd7fb945:/#
```
I hope this workaround helps you

**Comment by jasnzhuang** [comment]
> this solve my issue
> 
> ```
> brew install freetds openssl
> export LDFLAGS="-L/opt/homebrew/opt/freetds/lib -L/opt/homebrew/opt/openssl@3/lib"
> export CFLAGS="-I/opt/homebrew/opt/freetds/include"
> export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
> python -m pip install pymssql
> ```

it works on my Mac mini m2 with sonoma 14.3

**Comment by miguel2488** [comment]
> > this solve my issue
> > ```
> > brew install freetds openssl
> > export LDFLAGS="-L/opt/homebrew/opt/freetds/lib -L/opt/homebrew/opt/openssl@3/lib"
> > export CFLAGS="-I/opt/homebrew/opt/freetds/include"
> > export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
> > python -m pip install pymssql
> > ```
> 
> it works on my Mac mini m2 with sonoma 14.3

Worked for me too on an M1 with Sonoma 14.4.1

**Comment by termim** [comment]
Should be fixed in a24a3bf34b4a1c1510dce97ee6f8dae4708849ef
