### ISSUE TITLE
threadsafety: further understanding

### ISSUE THREAD

**Issue by dsmitran** [pymssql/pymssql#735]
Could you please help me understand the threadsafety of pymssql. 

> Module may be shared, but not connections.

Am I allowed to use a single connection in multiple threads but not concurrently (using a lock around each connection)? 

We are using up to CONNECTION_POOL_SIZE=20 different connections in multiple threads, but a given connection is only used by one thread at a given time.

**Comment by termim** [comment]
Connections could not be shared. You can see what is tested in threads here https://github.com/pymssql/pymssql/blob/master/tests/test_threaded.py

**Comment by DavidRueter** [comment]
In my experience, multi-threading worked perfectly / as expected version up to 2.1.5   But that was the last version where multi-threaded support worked properly.

Up through 2.1.5, yes--what @dsmitran asked was true:  "Am I allowed to use a single connection in multiple threads but not concurrently (using a lock around each connection)?"  I have done that extensively with great success.

On subsequent pymsql versions, my same working production code encounters an error when accessing a connection from a different thread (despite proper locking).  The error is:  pymssql._mssql.MSSQLDatabaseException: (0, b'Unknown error')

I would very much like to have threading work as in 2.1.5 but I have not been able to dig into this yet.

FYI, my code is at [github.com/davidrueter/theas](https://github.com/davidrueter/theas).  I'm happy to answer any questions or provide more information.


The full traceback: 

[E 220112 02:10:16 web:1789] Uncaught exception GET / (::1)
    HTTPServerRequest(protocol='http', host='localhost:8535', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Projects\Theas\venv_py38_theas\lib\site-packages\tornado\web.py", line 1704, in _execute
        result = await result
      File "C:\Projects\Theas\venv_py38_theas\lib\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:/Projects/Theas/TheasServer.py", line 3251, in get
        self.session = yield self.wait_for_session()
      File "C:\Projects\Theas\venv_py38_theas\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\Projects\Theas\venv_py38_theas\lib\site-packages\tornado\gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "C:/Projects/Theas/TheasServer.py", line 2986, in wait_for_session
        this_sess.authenticate(user_token=self.cookie_usertoken)
      File "C:/Projects/Theas/TheasServer.py", line 1588, in authenticate
        proc = ThStoredProc('theas.spdoAuthenticateUser', self)
      File "C:/Projects/Theas/TheasServer.py", line 455, in __init__
        self._storedproc = self.th_session.sql_conn.init_procedure(self.stored_proc_name)
      File "src\pymssql\_mssql.pyx", line 1421, in pymssql._mssql.MSSQLConnection.init_procedure
      File "src\pymssql\_mssql.pyx", line 1634, in pymssql._mssql.MSSQLStoredProcedure.__init__
      File "src\pymssql\_mssql.pyx", line 1800, in pymssql._mssql.check_cancel_and_raise
      File "src\pymssql\_mssql.pyx", line 1846, in pymssql._mssql.raise_MSSQLDatabaseException
    pymssql._mssql.MSSQLDatabaseException: (0, b'Unknown error')
