### ISSUE TITLE
Multi-thread support broken after 2.1.5

### ISSUE THREAD

**Issue by DavidRueter** [pymssql/pymssql#737]
I have multi-threaded code that uses pymsql that has worked well in production for a number of years.  This same code encounters an error when pymssql is on a version newer than 2.1.5.  The error occurs when a SQL connection is accessed from a different thread (despite proper locking.)

The error is:  pymssql._mssql.MSSQLDatabaseException: (0, b'Unknown error')

The use case:  Theas is a database-driven web application server based on Tornado.  When a browser requests a URL, Theas establishes a session (in memory at the web server).  That session includes among other things a SQL connection dedicated to that session.  A session cookie is set on the browser.

The session is locked while the server is preparing a response to a request and is unlocked once the response is set.  In this way the session can be accessed only from a single thread at a time.

Subsequent requests from the browser provide the session cookie.  The session is looked up in a list (properly locking the global list while accessing the list).  Once retrieved, the system waits until the session is unlocked (if it is locked), and then locks the session.

FYI, my code is at [github.com/davidrueter/theas](https://github.com/davidrueter/theas).  I'm happy to answer any questions or provide more information.  The wiki on GitHub provides additional information and rationale for the architecture.

The full traceback: 

```
[E 220112 02:10:16 web:1789] Uncaught exception GET / (::1)
    HTTPServerRequest(protocol='http', host='localhost:8535', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Projects\Theas\venv_py38_theas\lib\site-packages\tornado\web.py", line 1704, in _execute
        result = await result
      File "C:\Projects\Theas\venv_py38_theas\lib\site-packages\tornado\gen.py", line 769, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:/Projects/Theas/TheasServer.py", line 3251, in get
        self.session = yield self.wait_for_session()
      File "C:\Projects\Theas\venv_py38_theas\lib\site-packages\tornado\gen.py", line 762, in run
        value = future.result()
      File "C:\Projects\Theas\venv_py38_theas\lib\site-packages\tornado\gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "C:/Projects/Theas/TheasServer.py", line 2986, in wait_for_session
        this_sess.authenticate(user_token=self.cookie_usertoken)
      File "C:/Projects/Theas/TheasServer.py", line 1588, in authenticate
        proc = ThStoredProc('theas.spdoAuthenticateUser', self)
      File "C:/Projects/Theas/TheasServer.py", line 455, in __init__
        self._storedproc = self.th_session.sql_conn.init_procedure(self.stored_proc_name)
      File "src\pymssql\_mssql.pyx", line 1421, in pymssql._mssql.MSSQLConnection.init_procedure
      File "src\pymssql\_mssql.pyx", line 1634, in pymssql._mssql.MSSQLStoredProcedure.__init__
      File "src\pymssql\_mssql.pyx", line 1800, in pymssql._mssql.check_cancel_and_raise
      File "src\pymssql\_mssql.pyx", line 1846, in pymssql._mssql.raise_MSSQLDatabaseException
    pymssql._mssql.MSSQLDatabaseException: (0, b'Unknown error')
```

_Originally posted by @DavidRueter in https://github.com/pymssql/pymssql/issues/735#issuecomment-1010886901_

**Comment by DavidRueter** [comment]
Thank you for the review and the reply.  But "in 2.1.5 you have just been lucky"....that does not sound right, as we have thousands of hours of use on this code and have never once experience a problem.  Furthermore it was not just 2.1.5 that worked, but earlier versions as well.

Help me understand why this pattern would not be supported / would be unsafe:

1.  Create a thread
2.  In that thread create a connection
3.  Save a reference to the connection in a global variable
4.  Lock the global variable to prevent other threads from accessing it
5.  Do something with the connection
6.  Stop using the connection
7.  Release the lock
...
8.  Create a new thread
9.  Verify the global variable is not locked (wait for it if needed)
10.  Lock the global to prevent other threads from accessing it
11.  Retrieve the connection
12. Do something with the connection
13.  Stop using the connection,
14.  Release the lock

... and repeat
