### ISSUE TITLE
Cannot install pymssql on CentOS 7

### ISSUE THREAD

**Issue by riahc3** [pymssql/pymssql#748]
Hello

I am trying to install pymssql on a CentOS 7 installation but cannot.

Unless indicated, the commands are ran as root.

This starting point:

 ```
pip install -U pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/88/d9/761f0b1e0551a3559afe4d34bd9bf68fc8de3292363b3775dda39b62ce84/pip-22.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gS_UOf/pip/setup.py", line 7
        def read(rel_path: str) -> str:
                         ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gS_UOf/pip/
You are using pip version 8.1.2, however version 22.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

```
 pip install pymssql
Collecting pymssql
  Using cached https://files.pythonhosted.org/packages/4b/5f/e1707ea81e8ed367ecb919026370353564ce086b6b74fa51823c666acf09/pymssql-2.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BAbwpp/pymssql/setup.py", line 54
        raise Exception(f"Unsupported environment value {env_name}={val}")
                                                                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BAbwpp/pymssql/
You are using pip version 8.1.2, however version 22.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```
I attempt to upgrade pip but get a similar error

```
 pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/88/d9/761f0b1e0551a3559afe4d34bd9bf68fc8de3292363b3775dda39b62ce84/pip-22.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-guRIAG/pip/setup.py", line 7
        def read(rel_path: str) -> str:
                         ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-guRIAG/pip/
You are using pip version 8.1.2, however version 22.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Is there something I am doing incorrectly? Is there a alternative way to install this package?

Thank you

**Comment by termim** [comment]
- The last supported pymssql version for python2 is 2.1.5.
- It is not recommended to run pip as a root unless you are running in some kind of CI container.
