### ISSUE TITLE
Under high load I am getting strange errors

### ISSUE THREAD

**Issue by williambrach** [pymssql/pymssql#801]
**Describe the bug**
A clear and concise descHello,

I am currently attempting to conduct load testing on my FastAPI-based application which uses an MS SQL server with an MSSQL database hosted on Azure. As the load increases, I am encountering some Python "unknown" errors that are not being generated by my application.

Here is the setup for the database:
```python
engine = create_engine(SQLALCHEMY_DATABASE_URL, pool_size=20, max_overflow=10)
SessionLocal = scoped_session(
    sessionmaker(autocommit=False, autoflush=False, bind=engine)
)

Base = declarative_base()
Base.query = SessionLocal.query_property()
```
I am creating session objects for each call as described in the FastAPI documentation:
```python
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@router.post("/wine")
async def wineUrlWineInfo(
    wineUrl: wineUrl, response: Response, db: Session = Depends(get_db)
):
```

Attached are the stack traces for these errors.
```
pocketsomm-wine-cellar     self._close_impl()                                                                                                                                                                      
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2625, in _close_impl                                                                                                       
 pocketsomm-wine-cellar     self._connection_rollback_impl()                                                                                                                                                                        
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2617, in _connection_rollback_impl                                                                                         
 pocketsomm-wine-cellar     self.connection._rollback_impl()                                                                                                                                                                        
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1059, in _rollback_impl                                                                                                    
 pocketsomm-wine-cellar     self._handle_dbapi_exception(e, None, None, None, None)                                                                                                                                                 
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2128, in _handle_dbapi_exception                                                                                           
 pocketsomm-wine-cellar     util.raise_(exc_info[1], with_traceback=exc_info[2])                                                                                                                                                    
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_                                                                                                             
 pocketsomm-wine-cellar     raise exception                                                                                                                                                                                         
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1057, in _rollback_impl                                                                                                    
 pocketsomm-wine-cellar     self.engine.dialect.do_rollback(self.connection)                                                                                                                                                        
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mssql/base.py", line 2847, in do_rollback                                                                                               
 pocketsomm-wine-cellar     super(MSDialect, self).do_rollback(dbapi_connection)                                                                                                                                                    
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback                                                                                                     
 pocketsomm-wine-cellar     dbapi_connection.rollback()                                                                                                                                                                             
 pocketsomm-wine-cellar   File "src/pymssql/_pymssql.pyx", line 316, in pymssql._pymssql.Connection.rollback                                                                                                                        
 pocketsomm-wine-cellar   File "src/pymssql/_pymssql.pyx", line 300, in pymssql._pymssql.Connection.rollback                                                                                                                        
 pocketsomm-wine-cellar   File "src/pymssql/_mssql.pyx", line 1055, in pymssql._mssql.MSSQLConnection.execute_non_query                                                                                                             
 pocketsomm-wine-cellar   File "src/pymssql/_mssql.pyx", line 1076, in pymssql._mssql.MSSQLConnection.execute_non_query                                                                                                             
 pocketsomm-wine-cellar   File "src/pymssql/_mssql.pyx", line 1250, in pymssql._mssql.MSSQLConnection.format_and_run_query                                                                                                          
 pocketsomm-wine-cellar   File "src/pymssql/_mssql.pyx", line 1788, in pymssql._mssql.check_cancel_and_raise                                                                                                                        
 pocketsomm-wine-cellar   File "src/pymssql/_mssql.pyx", line 1834, in pymssql._mssql.raise_MSSQLDatabaseException                                                                                                                  
 pocketsomm-wine-cellar pymssql._mssql.MSSQLDatabaseException: (0, b'Unknown error')                                                                                                                                                
 pocketsomm-wine-cellar INFO:     10.244.5.53:46644 - "POST /v1/list HTTP/1.1" 500 Internal Server Error
```

```
│ pocketsomm-wine-cellar Exception during reset or similar                                                                                                                                                                           
 pocketsomm-wine-cellar Traceback (most recent call last):                                                                                                                                                                          
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 757, in _finalize_fairy                                                                                                      
 pocketsomm-wine-cellar     fairy._reset(pool, transaction_was_reset)                                                                                                                                                               
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1016, in _reset                                                                                                              
 pocketsomm-wine-cellar     pool._dialect.do_rollback(self)                                                                                                                                                                         
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mssql/base.py", line 2847, in do_rollback                                                                                               
 pocketsomm-wine-cellar     super(MSDialect, self).do_rollback(dbapi_connection)                                                                                                                                                    
 pocketsomm-wine-cellar   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback                                                                                                     
 pocketsomm-wine-cellar     dbapi_connection.rollback()                                                                                                                                                                             
 pocketsomm-wine-cellar   File "src/pymssql/_pymssql.pyx", line 316, in pymssql._pymssql.Connection.rollback                                                                                                                        
 pocketsomm-wine-cellar   File "src/pymssql/_pymssql.pyx", line 300, in pymssql._pymssql.Connection.rollback                                                                                                                        
 pocketsomm-wine-cellar   File "src/pymssql/_mssql.pyx", line 1055, in pymssql._mssql.MSSQLConnection.execute_non_query                                                                                                             
 pocketsomm-wine-cellar   File "src/pymssql/_mssql.pyx", line 1076, in pymssql._mssql.MSSQLConnection.execute_non_query                                                                                                             
 pocketsomm-wine-cellar   File "src/pymssql/_mssql.pyx", line 1250, in pymssql._mssql.MSSQLConnection.format_and_run_query                                                                                                          
 pocketsomm-wine-cellar   File "src/pymssql/_mssql.pyx", line 1788, in pymssql._mssql.check_cancel_and_raise                                                                                                                        
 pocketsomm-wine-cellar   File "src/pymssql/_mssql.pyx", line 1834, in pymssql._mssql.raise_MSSQLDatabaseException                                                                                                                  
 pocketsomm-wine-cellar pymssql._mssql.MSSQLDatabaseException: (3971, b'The server failed to resume the transaction. Desc:3e00000015.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL
  Server\n')
```

```
│ (Background on this error at: https://sqlalche.me/e/14/e3q8) (wineCellar.py:394)                                                                                                                                                                  │
│ 2023-03-09 16:23:20,913 - application.main.routers.wineCellar - ERROR - ERROR MSG : (pymssql._pymssql.OperationalError) (0, b'Unknown error')  
```
Has anyone else encountered similar issues during high-load situations, or can someone offer assistance with setting up SQLAlchemy to handle high-demand scenarios?

**Comment by termim** [comment]
At least one error seems to come directly from MSSQL server: `3971, b'The server failed to resume the transaction. Desc:3e00000015`. May be server logs could explain it.
Also you could try to capture FreeTDS logs using `TDSDUMP` environment variable.

**Comment by williambrach** [comment]
@termim  thanks for your response. Database is hosted on Azure cloud so I am having issue to access logs :(

**Comment by andaa003** [comment]
Hello, Were you able to resolve this issue?

Im using **pymssql** and get the same 'Unknown' error.

                            try:
                                # Execute the check query for the current record
                                with db_conn.cursor() as cursor:
                                    cursor.execute(check_query_stg)
                                    result = cursor.fetchall()

                                    if not result:  # No matching records found, so proceed with the update
                                        try:
                                            with db_conn.cursor() as cursor:
                                                cursor.execute(update_query_stg)
                                                db_conn.commit()
                                        except Exception as update_error:
                                            logging.error(f"Failed to execute update query: {update_error}")
                                            logging.error(f"Update Query: {update_query_stg}")
                                            logging.error(f"Parameters: pkid={pkid}, OrderNbr={Order_ID__c}")
                                            logging.error(f"Traceback: {traceback.format_exc()}")
                                            sys.exit(1)  # Exit if the update fails
                            except Exception as check_error:
                                logging.error(f"Failed to execute check query: {check_error}")
                                logging.error(f"Check Query: {check_query_stg}")
                                logging.error(f"Parameters: pkid={pkid}, OrderNbr={Order_ID__c}")
                                logging.error(f"Traceback: {traceback.format_exc()}")
                                sys.exit(1)  # Exit if the check query fails
