### ISSUE TITLE
pymssql error while connecting to Azure Synapse

### ISSUE THREAD

**Issue by mrluthra** [pymssql/pymssql#815]
I am trying to use pymssql while connecting to Azure Synapse. It works perfectly for AzureSQL but for Azure Synapse, getting below error:

```
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 647, in pymssql._pymssql.connect
  File "src/pymssql/_mssql.pyx", line 2109, in pymssql._mssql.connect
  File "src/pymssql/_mssql.pyx", line 732, in pymssql._mssql.MSSQLConnection.__init__
pymssql._mssql.MSSQLDriverException: Could not set connection properties

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pymssql/_pymssql.pyx", line 656, in pymssql._pymssql.connect
pymssql._pymssql.InterfaceError: Could not set connection properties
```

**Comment by cwegener** [comment]
Have you tried searching the existing list of open issues?
https://github.com/pymssql/pymssql/issues/793
