### ISSUE TITLE
Adaptive Server connection failed

### ISSUE THREAD

**Issue by thesefer** [pymssql/pymssql#903]
**Describe the bug**
I am trying to open the connection to a MSSQL Server 2019 (15.0.4382.1) without any further actions. A connection does not seem to be possible due to the error thrown below.

**To Reproduce**
Example password provided, same length

```
import pymssql

l_usr = "SQL_Test_Dev_User"
l_pass = "jrH5_8gywXvTU-adSa3c"
l_srv = "Local-Server_DEV-DB.domain.net"
l_db = "my_accessible_db"

conn = pymssql.connect(l_srv, l_usr, l_pass, l_db, tds_version='7.4')
cursor = conn.cursor(as_dict=True)

conn.close()
```

**Expected behavior**
Working connection

**Current Behavior**
```
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 650, in pymssql._pymssql.connect
  File "src/pymssql/_mssql.pyx", line 2155, in pymssql._mssql.connect
  File "src/pymssql/_mssql.pyx", line 712, in pymssql._mssql.MSSQLConnection.__init__
  File "src/pymssql/_mssql.pyx", line 1881, in pymssql._mssql.maybe_raise_MSSQLDatabaseException
  File "src/pymssql/_mssql.pyx", line 1898, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (18456, b"Login failed for user 'SQL_Test_Dev_User'.DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (Local-Server_DEV-DB.domain.net)\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/main.py", line 8, in <module>
    conn = pymssql.connect(server, user, password, database, tds_version='7.4')
  File "src/pymssql/_pymssql.pyx", line 659, in pymssql._pymssql.connect
pymssql.exceptions.OperationalError: (18456, b"Login failed for user 'SQL_Test_Dev_User'.DB-Lib error message 20018, severity 14:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20002, severity 9:\nAdaptive Server connection failed (Local-Server_DEV-DB.domain.net)\n")
```

**Context (Environment)**
 - What are the OS, Python and FreeTDS versions?
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```
 - please include the output of the following command:
    `/<path to your python>/python -c "import pymssql; print(pymssql.version_info())"`
```
>>> import pymssql; print(pymssql.version_info())
System:
platform.system()       : Linux
platform.architecture() : ('64bit', 'ELF')
platform.libc_ver()     : ('glibc', '2.31')
Python:
sys.version             : 3.8.10 (default, Jul 29 2024, 17:02:10)
[GCC 9.4.0]
pymssql:
VERSION            : (2, 3, 0)
version            : 2.3.0
full_version       : 2.3.0
dbversion          : freetds v1.4.10
_mssql:
VERSION            : (2, 3, 0)
version            : 2.3.0
full_version       : 2.3.0
dbversion          : freetds v1.4.10
login_timeout      : 60
min_error_severity : 6
```

**Additional context**
Fresh venv with only pymssql installed.
```
(.venv) cat requirements.txt
pymssql==2.3.0
```

EDIT:

Using SSMS on a windows machine I can connect, verifying a working login. Authentication mode is "SQL Server Authentication" and not Windows Authentication.

**Comment by thesefer** [comment]
Got the table delivered but not the database name.
