### ISSUE TITLE
pymssql version 2.3.1: DBPROCESS is dead or not enabled

### ISSUE THREAD

**Issue by felix-bedag** [pymssql/pymssql#908]
**Describe the bug**
An auto update of pymssql to version 2.3.1 caused our data scripts to fail with the error `DBPROCESS is dead or not enabled`.
The error occurred after having successfully read some 10k rows batched with pandas dataframe.
Depending on the script the point of failure was different.

*Downgrading pymssql to version 2.3.0 fixed the issue.*

**To Reproduce**
I cannot provide easy repro steps.

**Expected behavior**
No `DBPROCESS is dead or not enabled` error when reading data.

**Current Behavior**
When querying data, the following error occurs:
```
[2024-08-28, 05:11:57 CEST] {pod_manager.py:447} INFO - [base] Traceback (most recent call last):
[2024-08-28, 05:11:57 CEST] {pod_manager.py:447} INFO - [base]   File "/usr/src/app/dags-logic/copy_data_from_views.py", line 668, in <module>
[2024-08-28, 05:11:57 CEST] {pod_manager.py:447} INFO - [base]     extract_and_load()
[2024-08-28, 05:11:57 CEST] {pod_manager.py:447} INFO - [base]   File "/usr/src/app/dags-logic/copy_data_from_views.py", line 579, in extract_and_load
[2024-08-28, 05:11:57 CEST] {pod_manager.py:447} INFO - [base]     df_record_numbers_view = extract_and_load_dataframe(
[2024-08-28, 05:11:57 CEST] {pod_manager.py:447} INFO - [base]   File "/usr/src/app/dags-logic/copy_data_from_views.py", line 282, in extract_and_load_dataframe
[2024-08-28, 05:11:57 CEST] {pod_manager.py:447} INFO - [base]     data = source_cur.fetchmany(chunksize)
[2024-08-28, 05:11:57 CEST] {pod_manager.py:447} INFO - [base]   File "src/pymssql/_pymssql.pyx", line 541, in pymssql._pymssql.Cursor.fetchmany
[2024-08-28, 05:11:58 CEST] {pod_manager.py:460} INFO - [base] pymssql.exceptions.OperationalError: (20047, b'DB-Lib error message 20047, severity 9:\nDBPROCESS is dead or not enabled\n')
```

**Context (Environment)**
 - Docker base image `python:3.10-slim`

**Comment by m1551ngn0** [comment]
Same
Fails when calling a procedure
2.3.0 works fine

**Comment by plessbd** [comment]
Same here
