### ISSUE TITLE
Disconnections for unknown reasons in Windows

### ISSUE THREAD

**Issue by joelabreurojas** [pymssql/pymssql#919]
**Describe the bug**
Hi, I'm trying to migrate some data into a MSSQL database, over +5000 rows, using single inserts. When I try this in Windows the connection fails for some unknown reason, this happens every now and then, but the data is inserted.

Yes, I can try using a bulk insert, but I would like to know if there is anything I can do in this case.

**To Reproduce**
Iterate over an array of dictionaries to insert them.

**Expected behavior**
Migrated +5000 lines without problems.

**Current Behavior**
Migrated ~400-500 lines and disconnected for unknown reason.

**Context (Environment)**
```powershell
System:
platform.system()       : Windows
platform.architecture() : ('64bit', 'WindowsPE')
Python:
sys.version             : 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]
pymssql:
VERSION            : (2, 3, 2)
version            : 2.3.2
full_version       : 2.3.2
dbversion          : freetds v1.4.23
_mssql:
VERSION            : (2, 3, 2)
version            : 2.3.2
full_version       : 2.3.2
dbversion          : freetds v1.4.23
login_timeout      : 60
min_error_severity : 6
```

**Additional context**
I'm using SQLite and MSSQL to handle data in my project.

Error message:
```powershell
  File "C:\Users\jabreu\Templates\DBFxSQL\dbfxsql\modules\sql\sql_connection.py", line 53, in _get_cursor
    connection: SQL[engine].Connection = SQL[engine].connect(
                                         ^^^^^^^^^^^^^^^^^^^^
  File "src\\pymssql\\_pymssql.pyx", line 662, in pymssql._pymssql.connect
pymssql.exceptions.InterfaceError: Connection to the database failed for an unknown reason.
```

Setup:

```python
# sql_connection.py
"""Communications with the SQL database"""

from collections.abc import Generator
from contextlib import contextmanager
from dbfxsql.constants.sql_libraries import SQL
from dbfxsql.helpers import formatters, file_manager

...

@contextmanager
def _get_cursor(engine: str, filepath: str) -> Generator:
    """Provides a context manager for establishing and closing a database connection."""

    if "SQLite" == engine:
        connection: SQL[engine].Connection = SQL[engine].connect(filepath)
    else:
        config: dict = file_manager.load_config()["engines"][engine]
        filename: str = formatters.decompose_file(filepath)[0]

        connection: SQL[engine].Connection = SQL[engine].connect(
            server=config["db_server"],
            user=config["db_user"],
            password=config["db_password"],
            database=filename,
            autocommit=True,
            tds_version="7.0",
        )

    cursor: SQL[engine].Cursor = connection.cursor()

    try:
        yield cursor
        connection.commit()
    finally:
        cursor.close()
        connection.close()
```

```python
# sql_libraries.py
import sqlite3
import pymssql

SQL: dict = {
    "SQLite": sqlite3,
    "MSSQL": pymssql,
}
```

**Comment by termim** [comment]
You can use `TDSDUMP` environment variable to see more information.
Also the whole stacktrace from the error could help.

**Comment by joelabreurojas** [comment]
> You can use `TDSDUMP` environment variable to see more information. Also the whole stacktrace from the error could help.

## TDSDUMP Output:

```powershell
# After several successful operations...
dblib.c:1850:dbnumcols(0000020129E42590)
dblib.c:2826:dbcount(0000020129E42590)
dblib.c:1850:dbnumcols(0000020129E42590)
dblib.c:1876:dbcolname(0000020129E42590, 1)
dblib.c:2975:dbcoltype(0000020129E42590, 1)
dblib.c:2084:dbnextrow(0000020129E42590)
dblib.c:2090:dbnextrow() dbresults_state = 2 (_DB_RES_RESULTSET_ROWS)

token.c:555:tds_process_tokens(0000020129EA3980, 000000E631BEE468, 0000000000000000, 0x1508)
util.c:179:Changed query state from PENDING to READING
token.c:570:processing result tokens.  marker is  d1(ROW)
token.c:1955:tds_process_row(): reading column 0
data.c:723:tds_get_data: type 38, varint size 1
data.c:767:tds_get_data(): wire column size is 4
util.c:179:Changed query state from READING to PENDING
buffering.h:313:buffer_transfer_bound_data(0000020129E425A0 4040 -1 0000020129E42590 0)

dblib.c:2177:leaving dbnextrow() returning -1 (REG_ROW/MORE_ROWS)
dblib.c:3357:dbdata(0000020129E42590, 1)
dblib.c:2975:dbcoltype(0000020129E42590, 1)
dblib.c:3332:dbdatlen(0000020129E42590, 1)
dblib.c:3340:dbdatlen() type = 38, len= 4
dblib.c:1491:dbclose(0000020129E42590)
dblib.c:236:dblib_del_connection(00007FF96CCCB190, 0000020129EA3980)

query.c:3804:tds_disconnect()
util.c:179:Changed query state from PENDING to DEAD
mem.c:665:tds_free_all_results()

# For this block, I have removed the username, password, and database.
dblib.c:278:dblib_release_tds_ctx(1)
dblib.c:6088:dbfreebuf(0000020129E42590)
dblib.c:709:dblogin(void)
dblib.c:764:dbsetlname(0000020129C78AF0, pymssql=2.3.2, 5)
dblib.c:949:dbsetlversion(0000020129C78AF0, 4)
dblib.c:764:dbsetlname(0000020129C78AF0, UTF-8, 10)
dblib.c:4267:dbsetlogintime(60)

log.c:187:Starting log file for FreeTDS 1.4.23
        on 2025-01-02 09:27:42 with debug flags 0x4fff.

dblib.c:1187:tdsdbopen(0000020129C78AF0, PC-0044:1433, [microsoft])
dblib.c:1213:tdsdbopen: dbproc->dbopts = 0000020129E15EC0
dblib.c:1224:tdsdbopen: tds_set_server(0000020129EA0D20, "PC-0044:1433")
dblib.c:251:dblib_get_tds_ctx(void)
dblib.c:8167:dbperror(0000000000000000, 20010, 0)
dblib.c:8235:dbperror: Calling dblib_err_handler with msgno = 20010; msg->msgtext = "Unable to allocate sufficient memory"
dblib.c:5086:dbdead(0000000000000000) [quite dead]
dblib.c:8257:dbperror: dblib_err_handler for msgno = 20010; msg->msgtext = "Unable to allocate sufficient memory" -- returns 2 (INT_CANCEL)
dblib.c:739:dbloginfree(0000020129C78AF0)
```

## Traceback Output

```powershell
Traceback (most recent call last):
  File "src\\pymssql\\_pymssql.pyx", line 650, in pymssql._pymssql.connect
  File "src\\pymssql\\_mssql.pyx", line 2158, in pymssql._mssql.connect
  File "src\\pymssql\\_mssql.pyx", line 713, in pymssql._mssql.MSSQLConnection.__init__
pymssql._mssql.MSSQLDriverException: Connection to the database failed for an unknown reason.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\jabreu\AppData\Local\poetry\venv\Scripts\dbfxsql.exe\__main__.py", line 7, in <module>
  File "C:\Users\jabreu\AppData\Local\poetry\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jabreu\AppData\Local\poetry\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\jabreu\Templates\DBFxSQL\dbfxsql\models\lazy_group.py", line 36, in invoke
    return self._impl.invoke(ctx)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jabreu\AppData\Local\poetry\venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jabreu\AppData\Local\poetry\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jabreu\AppData\Local\poetry\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jabreu\Templates\DBFxSQL\dbfxsql\cli.py", line 298, in migrate
    sync_controller.migrate(filenames, relations)
  File "C:\Users\jabreu\Templates\DBFxSQL\dbfxsql\modules\sync\sync_controller.py", line 38, in migrate
    _execute_operations(operations, destinies)
  File "C:\Users\jabreu\Templates\DBFxSQL\dbfxsql\modules\sync\sync_controller.py", line 102, in _execute_operations
    operation_functions[name](**values)
  File "C:\Users\jabreu\Templates\DBFxSQL\dbfxsql\modules\sync\sync_connection.py", line 9, in insert
    sql_controller.insert_row(engine, filename, table, fields)
  File "C:\Users\jabreu\Templates\DBFxSQL\dbfxsql\modules\sql\sql_controller.py", line 46, in insert_row
    if not sql_queries.table_exists(engine, filepath, table):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jabreu\Templates\DBFxSQL\dbfxsql\modules\sql\sql_queries.py", line 160, in table_exists
    return bool(sql_connection.fetch_one(engine, filepath, query)[0]["COUNT(1)"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jabreu\Templates\DBFxSQL\dbfxsql\modules\sql\sql_connection.py", line 25, in fetch_one
    with _get_cursor(engine, filepath) as cursor:
  File "C:\Python312\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\jabreu\Templates\DBFxSQL\dbfxsql\modules\sql\sql_connection.py", line 53, in _get_cursor
    connection: SQL[engine].Connection = SQL[engine].connect(
                                         ^^^^^^^^^^^^^^^^^^^^
  File "src\\pymssql\\_pymssql.pyx", line 662, in pymssql._pymssql.connect
pymssql.exceptions.InterfaceError: Connection to the database failed for an unknown reason.
```

---

I understand that the database is unable to allocate enough memory, causing a connection to fail for some unknown reason. This works fine on Linux, so maybe the database server's cache is overloaded with the number of individual requests. I will see if I can increase the database resources.

Let me know if you have any suggestions.

**Comment by termim** [comment]
It looks like you are opening new connection for every inserted row. If that is correct then server could be overloaded creating and destroying connections. I'd recommend to use single transaction for all inserted rows.

**Comment by joelabreurojas** [comment]
You are right.

First, I implemented a bulk insert version to confirm that the MSSQL connection itself was working correctly. The bulk insert operation was successful, so I modified the code to perform individual inserts, which worked well.

**Setup:**

```python
def fetch_none(
    engine: str,
    filepath: str,
    query: str | list,
    parameters: dict | list | None = None,
    execute_many: bool = False,
) -> None:
    """Executes a query that doesn't return values."""

    with _get_cursor(engine, filepath) as cursor:
        if execute_many:
            for parameter in parameters:
                cursor.execute(query, parameter)

            # cursor.executemany(query, parameters) # for bulk inserts
```

**Output:**

```powershell
❯ dbfxsql migrate
DONE Migrating... (0:00:05.78)
```

Thank you, @termim.
